
services:

  backend:
    image: le_backend
    build:
      context: .
    depends_on:
      database:
        condition: service_healthy
    environment:
      POSTGRES_DB_URL: ${DB_URL}
      POSTGRES_USERNAME: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET}
      EMAIL: ${EMAIL}
      EMAIL_APP_PASSWORD: ${EMAIL_APP_PASSWORD}

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB_NAME: ${DB_NAME}
      POSTGRES_USERNAME: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USERNAME} -d $${POSTGRES_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql
      - ./init-scripts:/docker-entrypoint-initdb.d

volumes:
  db-data: